<link rel="stylesheet" href="/vendor/css/licence.css">

<br>

<div class="bg-secondary text-white" style="opacity: .8;">

  <h2>Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)</h2>

  <p>
  Jedná se o lidsky čitelné shrnutí licence (nikoli o její náhradu). Zřeknutí se odpovědnosti.
  </p>
  <h3>Máte možnost:</h3>

  <p>Sdílet - kopírovat a šířit materiál na jakémkoli médiu nebo v jakémkoli formátu.
    Poskytovatel licence nemůže tyto svobody zrušit, pokud dodržujete licenční podmínky.</p>

  <h4>Podle následujících podmínek:</h4>
  <p>Přidělení - musíte uvést odpovídající údaje, odkaz na licenci a uvést, zda byly provedeny změny.
     byly provedeny změny. Můžete tak učinit jakýmkoli přiměřeným způsobem, nikoli však způsobem, který by naznačoval, že poskytovatel licence schvaluje vás nebo vaše
     použití.

    Nekomerční - Materiál nesmíte používat ke komerčním účelům.

    NoDerivatives - Pokud materiál remixujete, transformujete nebo na něm stavíte, nesmíte upravený materiál distribuovat.
    materiál.

    Žádná další omezení - Nesmíte uplatňovat právní podmínky nebo technologická opatření, která právně omezují
    ostatní v tom, co licence povoluje.</p>

  <h5>Upozornění:</h5>

  <p>Licenci nemusíte dodržovat u prvků materiálu, které jsou veřejně dostupné nebo u kterých vaše použití
     je povoleno na základě platné výjimky nebo omezení.
     Neposkytují se žádné záruky. Licence vám nemusí poskytnout všechna oprávnění potřebná pro zamýšlené použití.
     Například další práva, jako jsou práva na publicitu, soukromí nebo morální práva, mohou omezovat způsob, jakým materiál použijete.</p>

</div>