<link rel="stylesheet" href="http://wa.kevizb.cz/pristupnost.css">

<br>


<div class="bg-secondary" style="max-width: 100%;margin-left: auto; margin-right: auto; color: whitesmoke; opacity: .8">

    <div>
        <h2>Vzor prohlášení o přístupnosti</h2>
        <p>Prohlášení o přístupnosti podle zákona č. 99/2019 Sb. má jasně předepsanou strukturu. Popisuje, do
            jaké míry jsou stránky v souladu s <a
                href="https://pristupne-stranky.cz/zakon-a-standardy/pozadavky-na-shodu/">požadavky na
                přístupnost</a> a jak postupovat v případě zjištění
            neshody. Narozdíl od dřívější praxe <strong>neobsahuje</strong> popis, jak otevřít PDF a další
            dokumenty.
        </p>
    </div>
    <div>
        <h2>Prohlášení o přístupnosti</h2>
        <p>Obec Vzorová Lhota se zavazuje ke zpřístupnění obsahu svých internetových stránek v souladu se
            zákonem č. 99/2019 Sb., o přístupnosti internetových stránek a mobilních aplikací a o změně zákona
            č. 365/2000 Sb., o informačních systémech veřejné správy a o změně některých dalších zákonů, ve
            znění pozdějších předpisů, které provádějí směrnici Evropského parlamentu a Rady (EU)
            2016/2102.<br>Toto prohlášení o přístupnosti se vztahuje na internetové stránky vzorova-lhota.cz.
        </p>
    </div>
    <div>
        <h3>Stav souladu</h3>
        <p>Tyto webové stránky jsou <strong>částečně v souladu</strong> se zákonem č. 99/2019 Sb., ve znění
            pozdějších předpisů,
            z důvodu nesouladu nebo výjimek uvedených níže.</p>
    </div>
    <div>
        <h3>Nepřístupný obsah</h3>
        <p>Niže uvedený obsah není přístupný: </p>
        <ol>
            <li>
                z důvodu nesouladu se zákonem č. 99/2019 Sb., ve znění pozdějších předpisů;
                <ul>
                    <li>
                        Odkazy na náhledových fotografiích ve fotogaleriích nemají textový popis, protože
                        obrázky nemají uvedený alternativní text (kritéria 1.1.1 a 2.4.4 standardu WCAG 2.1).
                        Vzhledem k množství fotografií a kapacitám provozovatele webu by doplnění smysluplného
                        alternativní text ke všem fotografiím způsobilo nepřiměřenou zátěž (podle § 7 zákona)
                    </li>
                </ul>
            </li>
            <li>
                jelikož nespadá do oblasti působnosti platných právních předpisů;
                <ul>
                    <li>
                        Videa na internetových stránkách neobsahují ani titulky ani audio popis či alternativu
                        (kritéria 1.2.1 a 1.2.2 standardu WCAG 2.1), na základě výjimky podle § 13 odstavce 4
                        zákona č. 99/2019 Sb.
                    </li>
                </ul>
            </li>

        </ol>
    </div>
    <div>
        <h3>Vypracování tohoto prohlášení o přístupnosti</h3>
        <p>Toto prohlášení bylo vypracováno dne 17.02.2023.</p>
        <p>Prohlášení bylo vypracováno posouzením provedeným třetí stranou – zpracovateli těchto internetových
            stránek tzn. Jaroslav Šperka & Dominik Sochůrek & Davik Kubík</p>
        <p>Při posuzování se sledovala shoda s kritérii uvedenými v Metodickém pokynu k zákonu č. 99/2019 Sb.,
            ve znění pozdějších předpisů a standardu Web Content Accessibility Guidelines – WCAG 2.1.</p>
    </div>
    <div>
        <h3>Zpětná vazba a kontaktní údaje</h3>
        <p>Vaše náměty či informace o problémech při zobrazování stránek, stejně jako dotazy, návrhy nebo
            připomínky týkající se obsahu webu či důvodného podezření, že webová stránka nesplňuje požadavky
            zákona č. 99/2019 Sb., ve znění pozdějších předpisů, včetně možnosti podat podnět vůči příslušným
            státním orgánům, můžete psát na adresu: <a href="mailto:kubik@spsejecna.cz">kubik@spsejecna.cz</a>
        </p>
        <p>Kontakt na osobu odpovědnou za přístupnost stránek a za zpracování žádostí zaslaných prostřednictvím
            mechanismu zpětné vazby:</p>
        <p>Střední průmyslová škola elektrotechnická<br>
            Ječná 30, 120 00 Praha 2<br>
            email: kubik@spsejecna.cz</p>
    </div>
    <div>
        <h3>Postup pro prosazování práva</h3>
        <p>V případě neuspokojivé odpovědi na zpětnou vazbu dle předchozího odstavce, můžete kontaktovat
            příslušný orgán pro prosazování práva:</p>
        <p>
            Ředitelství odboru, kabinet ŘŠ<br>
            Ječná 30, 120 00 Praha 2<br>
            <a href="mailto:mandik@spsejecna.cz">email: mandik@spsejecna.cz</a>
        </p>
    </div>
    <div>
        <h3>Zásady používání souborů cookies</h3>
        <p>Náš web <strong>nepoužívá</strong> soubory cookies!</p>
    </div>

</div>
